import { Link, useForm, usePage } from '@inertiajs/react';
import { motion } from 'framer-motion';
import { ChevronRight, ExternalLink, FileText, Trash2 } from 'lucide-react';
import React from 'react';
import ConfirmConceptSubmissionActionModal from '@/components/Student/ConfirmConceptSubmissionActionModal';
import StudentLayout from '../_layout';

type GroupSummary = {
    id: number;
    name: string;
    programSetName?: string | null;
    academicYear?: string | null;
};

type DocumentDetails = {
    id: number;
    source: 'Uploaded by Group' | 'Generated by System' | string;
    title: string;
    requirementType: string;
    stage: string;
    submittedAt?: string | null;
    instructorStatus: 'Submitted' | 'Approved' | 'Revision Required' | string;
    adviserStatus: 'Submitted' | 'Approved' | 'Revision Required' | string;
    mimeType?: string | null;
    fileSizeLabel?: string | null;
    fileUrl?: string | null;
    signedBy?: string | null;
    canRemove?: boolean;
    removeUrl?: string | null;
};

type StudentDocumentShowProps = {
    group: GroupSummary;
    isGroupLeader?: boolean;
    document: DocumentDetails;
    flash?: {
        success?: string;
    };
};

const statusPillClass = (status: string): string => {
    if (status === 'Approved') {
        return 'border-emerald-300 bg-emerald-100 text-emerald-800';
    }

    if (status === 'Revision Required') {
        return 'border-amber-200 bg-amber-100 text-amber-700';
    }

    return 'border-slate-200 bg-slate-100 text-slate-700';
};

const StudentDocumentShow = () => {
    const { props } = usePage<StudentDocumentShowProps>();
    const group = props.group;
    const isGroupLeader = props.isGroupLeader ?? false;
    const document = props.document;
    const successMessage = props.flash?.success ?? '';

    const [isDeleteConfirmationOpen, setIsDeleteConfirmationOpen] = React.useState(false);
    const deleteForm = useForm({});

    const groupLabel = `${group.name}${group.programSetName ? ` · ${group.programSetName}` : ''}${group.academicYear ? ` · ${group.academicYear}` : ''}`;

    const handleConfirmDelete = () => {
        if (!document.removeUrl) {
            return;
        }

        deleteForm.delete(document.removeUrl, {
            preserveScroll: true,
            preserveState: false,
        });
    };

    return (
        <StudentLayout title="Document File Viewer" subtitle="Review your selected group document">
            <div className="space-y-5">
                <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-slate-500">
                    <Link href="/student/dashboard" className="font-medium text-slate-600 transition-colors hover:text-slate-900">
                        Dashboard
                    </Link>
                    <ChevronRight className="h-3 w-3 text-slate-400" />
                    <Link href="/student/documents" className="font-medium text-slate-600 transition-colors hover:text-slate-900">
                        Group Documents
                    </Link>
                    <ChevronRight className="h-3 w-3 text-slate-400" />
                    <span className="font-semibold text-slate-800" aria-current="page">
                        View File
                    </span>
                </nav>

                <motion.section
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"
                >
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                        <div className="min-w-0 flex-1 space-y-2">
                            <div className="flex flex-wrap items-center gap-2">
                                <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-2.5 py-1 text-[11px] font-semibold tracking-wide text-slate-700 uppercase">
                                    <FileText className="h-3.5 w-3.5" />
                                    {document.source}
                                </span>
                                <span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusPillClass(document.instructorStatus)}`}>
                                    Instructor: {document.instructorStatus}
                                </span>
                            </div>

                            <div className="min-w-0">
                                <h3 className="max-w-3xl text-base leading-snug font-semibold break-words text-slate-900">{document.title}</h3>
                                <p className="mt-1 text-xs text-slate-500">{groupLabel}</p>
                            </div>
                        </div>

                        <div className="flex shrink-0 flex-row items-center justify-end gap-2">
                            {document.fileUrl ? (
                                <a
                                    href={document.fileUrl}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="inline-flex items-center gap-2 rounded-lg border border-emerald-200 bg-white px-3 py-2 text-xs font-semibold text-emerald-700 transition hover:bg-emerald-50"
                                >
                                    <ExternalLink className="h-4 w-4" />
                                    Open in New Tab
                                </a>
                            ) : null}

                            {isGroupLeader && document.canRemove ? (
                                <button
                                    type="button"
                                    onClick={() => setIsDeleteConfirmationOpen(true)}
                                    className="inline-flex items-center gap-2 rounded-lg border border-rose-200 bg-white px-3 py-2 text-xs font-semibold text-rose-700 transition hover:bg-rose-50"
                                >
                                    <Trash2 className="h-4 w-4" />
                                    Remove File
                                </button>
                            ) : null}
                        </div>
                    </div>

                    {successMessage !== '' ? (
                        <div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-700">
                            {successMessage}
                        </div>
                    ) : null}
                </motion.section>

                <motion.section
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.05 }}
                    className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"
                >
                    <div className="flex min-h-[72vh] flex-col lg:flex-row">
                        <aside className="border-b border-slate-200 bg-slate-50/90 p-4 lg:w-80 lg:border-r lg:border-b-0">
                            <div className="space-y-3">
                                <div className="rounded-xl border border-slate-200 bg-white p-3">
                                    <p className="text-[11px] font-semibold tracking-wide text-slate-500 uppercase">Requirement</p>
                                    <p className="mt-1 text-xs font-semibold text-slate-900">{document.requirementType}</p>
                                    <p className="mt-1 text-[11px] text-slate-500">Stage: {document.stage}</p>
                                </div>

                                <div className="rounded-xl border border-slate-200 bg-white p-3 text-xs text-slate-700">
                                    <div className="space-y-2">
                                        <p>
                                            <span className="font-semibold text-slate-800">Uploaded / Signed:</span> {document.submittedAt ?? '—'}
                                        </p>
                                        <p>
                                            <span className="font-semibold text-slate-800">Signed By:</span> {document.signedBy ?? 'Not applicable'}
                                        </p>
                                        <p>
                                            <span className="font-semibold text-slate-800">File Size:</span> {document.fileSizeLabel ?? 'Unavailable'}
                                        </p>
                                        <p>
                                            <span className="font-semibold text-slate-800">Mime Type:</span> {document.mimeType ?? 'application/pdf'}
                                        </p>
                                    </div>
                                </div>

                                <div className="rounded-xl border border-slate-200 bg-white p-3 text-xs text-slate-700">
                                    <div className="space-y-2">
                                        <p className="font-semibold text-slate-800">Status Summary</p>
                                        <div className="flex flex-wrap gap-2">
                                            <span
                                                className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusPillClass(document.instructorStatus)}`}
                                            >
                                                Instructor: {document.instructorStatus}
                                            </span>
                                            <span
                                                className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusPillClass(document.adviserStatus)}`}
                                            >
                                                Adviser: {document.adviserStatus}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </aside>

                        <div className="flex-1 bg-slate-100 p-4 lg:p-5">
                            {document.fileUrl ? (
                                <iframe
                                    key={document.fileUrl}
                                    src={`${document.fileUrl}#toolbar=1&navpanes=0&scrollbar=1&view=FitH`}
                                    title={document.title}
                                    className="h-[70vh] w-full rounded-xl border border-slate-200 bg-white lg:h-full lg:min-h-[72vh]"
                                />
                            ) : (
                                <div className="flex h-[70vh] items-center justify-center rounded-xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-500 lg:h-full lg:min-h-[72vh]">
                                    File preview is unavailable for this document.
                                </div>
                            )}
                        </div>
                    </div>
                </motion.section>
            </div>

            <ConfirmConceptSubmissionActionModal
                open={isDeleteConfirmationOpen}
                title="Remove Document"
                message="This permanently deletes the selected uploaded file and removes it from your group document records."
                confirmLabel="Remove File"
                tone="danger"
                processing={deleteForm.processing}
                onClose={() => setIsDeleteConfirmationOpen(false)}
                onConfirm={handleConfirmDelete}
            />
        </StudentLayout>
    );
};

export default StudentDocumentShow;
